# NumPy indexing and selection 

In [1]:
import numpy as np

In [9]:
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [10]:
arr[8]

8

In [11]:
arr[0:21]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [12]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [13]:
arr[9:21]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
arr[:21]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [15]:
arr[0:5] = 100

In [16]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20])