In [2]:
import numpy as np

In [3]:
my_list = [1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3], [3,4,5], [6,7,8]]
my_mat

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

# Range method

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# Use this function if you want an array of all the same numbers

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# numpy.linspace

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)



Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the interval [start, stop].

The endpoint of the interval can optionally be excluded.

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

# numpy.eye

(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)


Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
Nint
Number of rows in the output.
Mint, optional
Number of columns in the output. If None, defaults to N.
kint, optional
Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.
dtypedata-type, optional
Data-type of the returned array.
order{‘C’, ‘F’}, optional
Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.


In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# numpy.random.rand

random.rand(d0, d1, ..., dn)

Random values in a given shape.

Parameters: d0, d1, …, dnint, optional

The dimensions of the returned array, must be non-negative. 
If no argument is given a single Python float is returned.

Returns: outndarray, shape (d0, d1, ..., dn)

Random values.

In [16]:
np.random.rand(5)

array([0.48373059, 0.24465111, 0.40800546, 0.55484672, 0.10749047])

In [17]:
np.random.rand(5,5)

array([[0.42988173, 0.13769252, 0.38743568, 0.49532744, 0.48190173],
       [0.15981316, 0.70513525, 0.36458321, 0.05482889, 0.59674362],
       [0.09613403, 0.54126822, 0.46491581, 0.3260682 , 0.97327009],
       [0.80501994, 0.03725608, 0.0764754 , 0.19748018, 0.41729612],
       [0.71711254, 0.2246615 , 0.77571811, 0.31133279, 0.15298748]])

# numpy.random.randn

random.randn(d0, d1, ..., dn)
Return a sample (or samples) from the “standard normal” distribution.

If positive int_like arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1. 
A single float randomly sampled from the distribution is returned if no argument is provided.

Parameters
d0, d1, …, dnint, optional
The dimensions of the returned array, must be non-negative. 
If no argument is given a single Python float is returned.
Returns
Zndarray or float

A (d0, d1, ..., dn)-shaped array of floating-point samples from the standard normal distribution, or a single such float if no parameters were supplied.

In [18]:
np.random.randn(2)

array([-1.3884105 ,  0.01267726])

In [19]:
np.random.randn(5,5)

array([[ 0.81234805, -0.89668887, -0.05643338, -1.05062065, -0.58434811],
       [-0.65935001,  0.30887888, -1.05124116,  0.72377745, -2.17275125],
       [ 0.08959167, -0.50316758, -0.18290461, -1.77727783,  0.5022324 ],
       [ 0.01135388, -0.20470005, -0.41483362, -0.96039817,  2.48205604],
       [-0.60706313, -2.13163979, -1.25909288, -0.466532  ,  0.51695064]])

# numpy.random.randint


random.randint(low, high=None, size=None, dtype=int)

Return random integers from low (inclusive) to high (exclusive).

Return random integers from the “discrete uniform” distribution of the specified dtype in the “half-open” interval 

[low, high). 
If high is None (the default), 
then results are from [0, low).

In [20]:
np.random.randint(1,100)

86

### now if you want specific amount of integers just indicate it after second index

In [21]:
np.random.randint(1,100,10)

array([19, 48, 79, 39,  3, 20,  9,  6, 81, 20])

In [22]:
np.random.randint(1,100)

97

In [23]:
arr = np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
np.random.randint(0,50,10)

array([ 8, 38, 34, 14, 14,  4, 23, 48, 27, 27])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
aranarr = np.random.randint(0,50,10)

In [28]:
aranarr

array([12, 25, 10,  9,  5, 49, 41, 33, 29, 34])

In [29]:
aranarr.max()

49

In [30]:
aranarr.min()

5

In [31]:
aranarr.argmax()

5

In [32]:
aranarr.argmin()

4

In [33]:
aranarr.dtype

dtype('int64')

In [34]:
from numpy.random import randint 

In [38]:
randint(2,10)

2

# NumPy Indexing and Selection

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[1:5]

array([1, 2, 3, 4])

## if you put nothing and identify only the end parameter, it will an array with all elements in it up to the end point


In [43]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
slice_of_arr = arr[0:6]

In [46]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [47]:
slice_of_arr[:] = 99

In [48]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [49]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [50]:
arr_copy = arr.copy()

In [51]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [52]:
arr_copy[:] = 100

In [53]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [55]:
arr_2d = np.array([[5,10,15], [9,21,12], [12,12,24]])

In [56]:
arr_2d

array([[ 5, 10, 15],
       [ 9, 21, 12],
       [12, 12, 24]])

In [57]:
arr_2d[0][0]

5

In [58]:
arr_2d[0][1]

10